import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import dynamic from "next/dynamic";
//@ts-ignore
const Background = dynamic(() => import("../components/Background"), {
  ssr: false,
});

export default function Home() {
  return (
    <div>
      <Background />

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container} suppressHydrationWarning={true}></main>
    </div>
  );
}
